spring:
  main:
    allow-circular-references: true
  flyway:
    depends-on: entityManagerFactory
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: toddy
    password: toddy
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
